verify-contract:
	-forge verify-contract \
	  --rpc-url https://rpc.gnosischain.com \
	  --verifier blockscout \
	  --verifier-url 'https://gnosis.blockscout.com/api/' \
	  0xBF2f2337337508ED26855Ef0482dD221c9752216 \
	  src/FluidProposals.sol:FluidProposals --compiler-version 0.8.27
